import { NewTemplate } from './schema';

export const seedTemplates: Omit<NewTemplate, 'id' | 'createdAt' | 'updatedAt' | 'createdBy'>[] = [
  // Issue Templates
  {
    nodeType: 'issue',
    name: 'Client Onboarding',
    description: 'New client has signed contract and needs to be onboarded',
    category: 'Client Management',
    tags: ['onboarding', 'client', 'sales'],
    metadata: { priority: 'high', estimatedTime: '2 weeks' },
  },
  {
    nodeType: 'issue',
    name: 'System Downtime',
    description: 'Technical issue affecting system operations and user access',
    category: 'Technical',
    tags: ['incident', 'technical', 'urgent'],
    metadata: { priority: 'critical', impact: 'high' },
  },
  {
    nodeType: 'issue',
    name: 'Low Conversion Rate',
    description: 'Sales metrics showing conversion rate below target threshold',
    category: 'Business',
    tags: ['metrics', 'sales', 'conversion'],
    metadata: { priority: 'medium', threshold: '2%' },
  },
  {
    nodeType: 'issue',
    name: 'Customer Complaint',
    description: 'Customer has reported dissatisfaction with product or service',
    category: 'Client Management',
    tags: ['support', 'customer', 'feedback'],
    metadata: { priority: 'high', sla: '24 hours' },
  },
  {
    nodeType: 'issue',
    name: 'Budget Overrun',
    description: 'Project expenses exceeding allocated budget',
    category: 'Business',
    tags: ['finance', 'budget', 'project'],
    metadata: { priority: 'high', alertThreshold: '80%' },
  },

  // Action Templates
  {
    nodeType: 'action',
    name: 'Discovery Call',
    description: 'Schedule and conduct stakeholder interview to understand requirements',
    category: 'Process',
    tags: ['meeting', 'discovery', 'requirements'],
    metadata: { duration: '60 minutes', requiredParticipants: ['PM', 'Client'] },
  },
  {
    nodeType: 'action',
    name: 'Deploy Hotfix',
    description: 'Emergency code deployment to resolve critical production issue',
    category: 'Technical',
    tags: ['deployment', 'urgent', 'fix'],
    metadata: { priority: 'critical', requiredApprovals: 2 },
  },
  {
    nodeType: 'action',
    name: 'A/B Testing Setup',
    description: 'Configure and launch conversion optimization experiment',
    category: 'Process',
    tags: ['testing', 'optimization', 'analytics'],
    metadata: { duration: '1 week', sampleSize: '1000+' },
  },
  {
    nodeType: 'action',
    name: 'Client Training Session',
    description: 'Conduct product training for client team members',
    category: 'Client Management',
    tags: ['training', 'education', 'onboarding'],
    metadata: { duration: '2 hours', format: 'virtual' },
  },
  {
    nodeType: 'action',
    name: 'Code Review',
    description: 'Review pull request for quality, security, and best practices',
    category: 'Technical',
    tags: ['development', 'quality', 'review'],
    metadata: { estimatedTime: '30 minutes', requiredReviewers: 2 },
  },
  {
    nodeType: 'action',
    name: 'Budget Analysis',
    description: 'Analyze spending patterns and identify cost optimization opportunities',
    category: 'Business',
    tags: ['finance', 'analysis', 'reporting'],
    metadata: { frequency: 'monthly', stakeholders: ['CFO', 'PM'] },
  },

  // Resource Templates
  {
    nodeType: 'resource',
    name: 'GoHighLevel',
    description: 'CRM and client scheduling platform for automation',
    category: 'Tools',
    tags: ['crm', 'automation', 'scheduling'],
    metadata: { url: 'https://gohighlevel.com', type: 'saas' },
  },
  {
    nodeType: 'resource',
    name: 'n8n',
    description: 'Workflow automation engine for connecting apps and services',
    category: 'Tools',
    tags: ['automation', 'integration', 'workflow'],
    metadata: { url: 'https://n8n.io', type: 'saas', selfHosted: true },
  },
  {
    nodeType: 'resource',
    name: 'Google Analytics',
    description: 'Website traffic analysis and conversion tracking platform',
    category: 'Tools',
    tags: ['analytics', 'tracking', 'metrics'],
    metadata: { url: 'https://analytics.google.com', type: 'saas' },
  },
  {
    nodeType: 'resource',
    name: 'Figma',
    description: 'Collaborative design tool for UI/UX and prototyping',
    category: 'Tools',
    tags: ['design', 'collaboration', 'prototyping'],
    metadata: { url: 'https://figma.com', type: 'saas' },
  },
  {
    nodeType: 'resource',
    name: 'GitHub',
    description: 'Version control and code collaboration platform',
    category: 'Tools',
    tags: ['development', 'version-control', 'collaboration'],
    metadata: { url: 'https://github.com', type: 'saas' },
  },
  {
    nodeType: 'resource',
    name: 'Slack',
    description: 'Team communication and collaboration platform',
    category: 'Tools',
    tags: ['communication', 'collaboration', 'messaging'],
    metadata: { url: 'https://slack.com', type: 'saas' },
  },

  // Deliverable Templates
  {
    nodeType: 'deliverable',
    name: 'Client Onboarding Report',
    description: 'Comprehensive summary of new client setup and configuration',
    category: 'Documentation',
    tags: ['report', 'onboarding', 'documentation'],
    metadata: { format: 'PDF', sections: ['Setup', 'Configuration', 'Training', 'Next Steps'] },
  },
  {
    nodeType: 'deliverable',
    name: 'Incident Post-Mortem',
    description: 'Detailed analysis of system incident including timeline and remediation',
    category: 'Documentation',
    tags: ['incident', 'analysis', 'report'],
    metadata: { format: 'Document', requiredSections: ['Timeline', 'Root Cause', 'Action Items'] },
  },
  {
    nodeType: 'deliverable',
    name: 'Test Results Dashboard',
    description: 'Visual dashboard showing A/B test performance metrics and insights',
    category: 'Analytics',
    tags: ['dashboard', 'metrics', 'reporting'],
    metadata: { format: 'Interactive', metrics: ['Conversion', 'Traffic', 'Revenue'] },
  },
  {
    nodeType: 'deliverable',
    name: 'Technical Specification',
    description: 'Detailed technical requirements and architecture document',
    category: 'Documentation',
    tags: ['technical', 'specifications', 'architecture'],
    metadata: { format: 'Markdown', sections: ['Requirements', 'Architecture', 'API'] },
  },
  {
    nodeType: 'deliverable',
    name: 'Monthly Performance Report',
    description: 'Executive summary of key business metrics and trends',
    category: 'Analytics',
    tags: ['report', 'metrics', 'executive'],
    metadata: { format: 'Presentation', frequency: 'monthly', audience: 'executives' },
  },
];
